### ISSUE TITLE
Batched inserts are failing

### ISSUE THREAD

**Issue by spyhunter99** [SQLDroid/SQLDroid#87]
Does this driver support addBatch, executeBatch, clearBatch and clearParameters? I'm having some issues with batched prepared statements, getting errors like the number of parameters doesn't match the batch insert count

**Comment by spyhunter99** [comment]
here's some relevant log output

````
08-13 13:20:44.559  2112  2147 V SQLDRoid: new SqlDRoid prepared statement from org.sqldroid.SQLDroidConnection@2c2c820
08-13 13:20:44.559  2112  2147 D SQLDroid: BEGIN TRANSACTION (autocommit off) 184 "Thread-184" org.sqldroid.SQLDroidConnection@2c2c820
08-13 13:20:44.561  2112  2147 V SQLDRoid: new SqlDRoid prepared statement from org.sqldroid.SQLDroidConnection@2c2c820
08-13 13:20:44.562  2112  2147 V SQLDRoid: new SqlDRoid prepared statement from org.sqldroid.SQLDroidConnection@2c2c820
08-13 13:20:44.562  2112  2147 V SQLDRoid: new SqlDRoid prepared statement from org.sqldroid.SQLDroidConnection@2c2c820
08-13 13:20:44.562  2112  2147 V SQLDRoid: new SqlDRoid prepared statement from org.sqldroid.SQLDroidConnection@2c2c820
08-13 13:20:44.562  2112  2147 V SQLDRoid: new SqlDRoid prepared statement from org.sqldroid.SQLDroidConnection@2c2c820
08-13 13:20:44.623  2112  2148 V SQLDroid: SQLiteDatabase execSQL: 185 "Thread-185" INSERT OR REPLACE INTO nodes (id,changeset,version,user,uid,timestamp,lat,lon) VALUES (?,?,?,?, ?,?,?,?);
08-13 13:21:14.624  2112  2148 W SQLiteConnectionPool: The connection pool for database '/sdcard/importTest.sqlite' has been unable to grant a connection to thread 185 (Thread-185) with flags 0x2 for 30.001001 seconds.
08-13 13:21:14.624  2112  2148 W SQLiteConnectionPool: Connections: 0 active, 1 idle, 0 available.
08-13 13:21:44.624  2112  2148 W SQLiteConnectionPool: The connection pool for database '/sdcard/importTest.sqlite' has been unable to grant a connection to thread 185 (Thread-185) with flags 0x2 for 60.001003 seconds.
08-13 13:21:44.624  2112  2148 W SQLiteConnectionPool: Connections: 0 active, 1 idle, 0 available.
08-13 13:22:14.626  2112  2148 W SQLiteConnectionPool: The connection pool for database '/sdcard/importTest.sqlite' has been unable to grant a connection to thread 185 (Thread-185) with flags 0x2 for 90.003006 seconds.
08-13 13:22:14.626  2112  2148 W SQLiteConnectionPool: Connections: 0 active, 1 idle, 0 available.
````

**Comment by spyhunter99** [comment]
Update: the previous log output was probably unrelated... 
````
08-13 13:30:16.665  2269  2283 D SQLDroid: BEGIN TRANSACTION (after commit) 188 "Thread-188" org.sqldroid.SQLDroidConnection@daf4066
08-13 13:30:16.674  2269  2283 V SQLDroid: SQLiteDatabase execSQL: 188 "Thread-188"
08-13 13:30:16.674  2269  2283 W System.err: java.lang.IllegalArgumentException: Too many bind arguments.  8 arguments were provided but the statement needs 0 arguments.
08-13 13:30:16.674  2269  2283 W System.err:    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:68)
08-13 13:30:16.674  2269  2283 W System.err:    at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
08-13 13:30:16.674  2269  2283 W System.err:    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
08-13 13:30:16.674  2269  2283 W System.err:    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1655)
08-13 13:30:16.674  2269  2283 W System.err:    at org.sqldroid.SQLiteDatabase.execSQL(SQLiteDatabase.java:140)
08-13 13:30:16.674  2269  2283 W System.err:    at org.sqldroid.SQLDroidPreparedStatement.executeBatch(SQLDroidPreparedStatement.java:269)
08-13 13:30:16.674  2269  2283 W System.err:    at org.osmdroid.reader.readers.OsmPullParserReader.read(OsmPullParserReader.java:214)
08-13 13:30:16.674  2269  2283 W System.err:    at org.osmdroid.reader.MainActivity$2.run(MainActivity.java:104)
08-13 13:30:16.674  2269  2283 W System.err:    at java.lang.Thread.run(Thread.java:818)
````
